FROM mcr.microsoft.com/dotnet/runtime:7.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["../Source/Inventory.DbUpdate/Inventory.DbUpdate.csproj", "Source/Inventory.DbUpdate/"]
COPY ["../Source/Inventory.Persistence/Inventory.Persistence.csproj", "Source/Inventory.Persistence/"]
COPY ["../Source/Inventory.Application/Inventory.Application.csproj", "Source/Inventory.Application/"]
COPY ["../Source/Inventory.Core/Inventory.Core.csproj", "Source/Inventory.Core/"]
COPY ["../Source/Sgtin/Sgtin.csproj", "Source/Sgtin/"]
RUN dotnet restore "Source/Inventory.DbUpdate/Inventory.DbUpdate.csproj"
COPY . .
WORKDIR "/src/Source/Inventory.DbUpdate"
RUN dotnet build "Inventory.DbUpdate.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Inventory.DbUpdate.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
CMD ["sh", "-c", "dotnet Inventory.DbUpdate.dll \"${DB_CONNECTION}\""]
